/*
 * openCypher Xtext - Slizaa Static Software Analysis Tools
 * Copyright © ${year} Code-Kontor GmbH and others (slizaa@codekontor.io)
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Code-Kontor GmbH - initial API and implementation
 */
/*
 * generated by Xtext 2.10.0
 */
package io.codekontor.opencypher.xtext.validation;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.regex.Pattern;

import io.codekontor.opencypher.xtext.openCypher.*;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.validation.Check;
import com.google.inject.name.Named;
import com.google.inject.Inject;

/**
 * This class implements custom validation rules for the openCypher language.
 *
 * Semantic rules defined here go beyond the capabilities of a context-free grammar,
 * allowing the editor to flag logical errors such as misplaced clauses or
 * incorrectly formatted literals.
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class OpenCypherValidator extends AbstractOpenCypherValidator {

	/** Regular expression to validate version numbers. */
	private static final Pattern VERSION_NUMBER_FORMAT = Pattern.compile("\\d*\\.\\d*");

	/** Regular expression to validate that decimal integers do not start with a leading zero. */
	private static final Pattern DECIMAL_INTEGER_FORMAT = Pattern.compile("[1-9]*\\d*");

	/** Unique error keys used to identify specific validation failures in the UI. */
	public static final String INVALID_VERSION_NUMBER_FORMAT = "invalidVersionNumber";
	public static final String INVALID_DECIMAL_INTEGER_FORMAT = "invalidDecimalInteger";
	public static final String INVALID_STATEMENT_COUNT = "invalidStatementCount";
	public static final String RETURN_NOT_AT_THE_END = "returnNotAtTheEnd";
	public static final String CYCLIC_INHERITANCE = "cyclicInheritance";
	public static final String DUPLICATE_NODE_TYPE = "duplicateNodeType";
	public static final String DUPLICATE_PROPERTY = "duplicateProperty";
	public static final String PROPERTY_SHADOWING = "propertyShadowing";

	/**
	 * Configuration setting to determine if a single file can contain multiple
	 * Cypher statements separated by semicolons.
	 */
	@Inject(optional=true)
	@Named("opencypher.allowMultipleStatements")
	private boolean allowMultipleStatements = true;

	/**
	 * Validates that the input contains the correct number of statements.
	 *
	 * If multiple statements are provided but the configuration disallows it,
	 * an error is attached to the statement list feature.
	 */
	@Check
	public void checkCypherFormat(Cypher cypher) {
		if (allowMultipleStatements) {
			return;
		}
		// Ensure that exactly one statement is present if multiple statements are restricted.
		if (cypher.getStatements().size() != 1) {
			error("There must be exactly one statement.",
					OpenCypherPackage.eINSTANCE.getCypher_Statements(), INVALID_STATEMENT_COUNT);
		}
	}

	/**
	 * Placeholder for legacy parameter validation.
	 */
	@Check
	public void checkLegacyParameterFormat(LegacyParameter legacyParameter) {
		// TODO check!
		// legacyParameter : '{' ws ( symbolicName | DecimalInteger ) ws '}' ;
	}

	/**
	 * Placeholder for standard parameter validation.
	 */
	@Check
	public void checkParameterFormat(Parameter parameter) {
		// TODO check!
		// parameter : '$' ( symbolicName | DecimalInteger ) ;
	}

	/**
	 * Placeholder for range literal validation.
	 */
	@Check
	public void checkRangeLiteralFormat(RangeLiteral rangeLiteral) {
		// TODO check!
		rangeLiteral.getLower();
		// TODO check!
		rangeLiteral.getUpper();
	}

	/**
	 * Verifies that decimal integer literals follow the required numeric format.
	 *
	 * Even though the lexer identifies these as numbers, this method ensures
	 * they meet domain-specific formatting rules.
	 */
	@Check
	public void checkDecimalIntegerFormat(DecimalInteger decimalInteger) {
		if (!DECIMAL_INTEGER_FORMAT.matcher(decimalInteger.getValue()).matches()) {
			error("Version number must have the following format: (digit)+'.'(digit)+",
					OpenCypherPackage.eINSTANCE.getDecimalInteger_Value(), INVALID_DECIMAL_INTEGER_FORMAT);
		}
	}

	/**
	 * Ensures that the Cypher version number is correctly formatted.
	 */
	@Check
	public void checkVersionNumberFormat(VersionNumber versionNumber) {
		if (versionNumber.getVersionNumber() != null) {
			if (!VERSION_NUMBER_FORMAT.matcher(versionNumber.getVersionNumber()).matches()) {
				error("Version number must have the following format: (digit)+'.'(digit)+",
						OpenCypherPackage.eINSTANCE.getVersionNumber_VersionNumber(), INVALID_VERSION_NUMBER_FORMAT);
			}
		}
	}

	/**
	 * Validates the placement of the RETURN clause within a query.
	 */
	@Check
	public void checkReturn(Return ret) {
		if (EcoreUtil2.getNextSibling(ret) != null) {
			error("RETURN can only be used once at the end of the query", ret,
					OpenCypherPackage.eINSTANCE.getReturn_Return(), RETURN_NOT_AT_THE_END);
		}
	}

	/**
	 * Verifies that there are no cycles in the inheritance hierarchy of NodeTypes.
	 * This prevents infinite loops when resolving properties or generating code.
	 * Example error: (:A => :B) and (:B => :A)
	 */
	@Check
	public void checkCyclicInheritance(NodeTypeDefinition nodeType) {
		if (nodeType.getSuperTypes() == null || nodeType.getSuperTypes().isEmpty()) return;
		Cypher root = (Cypher) EcoreUtil2.getRootContainer(nodeType);
		Map<String, NodeTypeDefinition> nodeTypeMap = new HashMap<>();
		for (NodeTypeDefinition nt : EcoreUtil2.getAllContentsOfType(root, NodeTypeDefinition.class)) {
			if (nt.getName() != null) nodeTypeMap.put(nt.getName(), nt);
		}
		Set<String> visited = new HashSet<>();
		Set<String> stack = new HashSet<>();
		if (hasCyclicPath(nodeType.getName(), nodeTypeMap, visited, stack)) {
			error("Cyclic inheritance detected: NodeType '" + nodeType.getName() + "' belongs to a closed loop chain.",
					nodeType, null, CYCLIC_INHERITANCE);
		}

	}

	private boolean hasCyclicPath(String current, Map<String, NodeTypeDefinition> map, Set<String> visited, Set<String> stack) {
		if (stack.contains(current)) return true;
		if (visited.contains(current)) return false;
		visited.add(current);
		stack.add(current);
		NodeTypeDefinition nt = map.get(current);
		if (nt != null && nt.getSuperTypes() != null) {
			for (String parentName : nt.getSuperTypes()) {
				if (hasCyclicPath(parentName, map, visited, stack)) return true;
			}
		}
		stack.remove(current);
		return false;
	}

	/**
	 * Ensures that each NodeType label is unique within the scope of the entire file.
	 * Duplicate labels would make it impossible to know which definition to use.
	 */
	@Check
	public void checkUniqueNodeType(NodeTypeDefinition nodeType) {
		if (nodeType.eContainer() instanceof RelationshipTypeDefinition) return;
		String name = nodeType.getName();
		if (name == null) return;
		Cypher root = (Cypher) EcoreUtil2.getRootContainer(nodeType);
		long count = EcoreUtil2.getAllContentsOfType(root, NodeTypeDefinition.class).stream()
				.filter(nt -> !(nt.eContainer() instanceof RelationshipTypeDefinition))
				.filter(nt -> name.equals(nt.getName()))
				.count();
		if (count > 1) error("NodeType '" + name + "' is already defined.", nodeType, null, DUPLICATE_NODE_TYPE);
	}

	/**
	 * Checks for duplicate property names within a single NodeType definition.
	 * Example error: (:Person { name :: string, name :: int })
	 */
	@Check
	public void checkUniqueProperties(TypePropertyMap map) {
		Set<String> propertyNames = new HashSet<>();
		for (TypeProperty prop : map.getProperties()) {
			String name = prop.getName();
			if (name == null) continue;

			if (propertyNames.contains(name)) {
				error("Duplicate property '" + name + "' in type definition.", prop, null, DUPLICATE_PROPERTY);
			}
			propertyNames.add(name);
		}
	}

	/**
	 * Warns if a NodeType redefines a property that already exists in its parent types.
	 * This can lead to confusion in the data model.
	 */
	@Check
	public void checkPropertyShadowing(NodeTypeDefinition nodeType) {
		if (nodeType.getSuperTypes() == null || nodeType.getSuperTypes().isEmpty() || nodeType.getProperties() == null) return;

		Cypher root = (Cypher) EcoreUtil2.getRootContainer(nodeType);
		Map<String, NodeTypeDefinition> nodeTypeMap = new HashMap<>();
		for (NodeTypeDefinition nt : EcoreUtil2.getAllContentsOfType(root, NodeTypeDefinition.class)) {
			if (nt.getName() != null) nodeTypeMap.put(nt.getName(), nt);
		}

		Set<String> inheritedProperties = new HashSet<>();
		for (String parentName : nodeType.getSuperTypes()) {
			collectInheritedPropertyNames(parentName, nodeTypeMap, inheritedProperties, new HashSet<>());
		}

		for (TypeProperty prop : nodeType.getProperties().getProperties()) {
			if (inheritedProperties.contains(prop.getName())) {
				warning("Property '" + prop.getName() + "' shadows a property defined in a parent type.", prop, null, PROPERTY_SHADOWING);
			}
		}
	}

	private void collectInheritedPropertyNames(String currentName, Map<String, NodeTypeDefinition> map, Set<String> results, Set<String> visited) {
		if (currentName == null || visited.contains(currentName)) return;
		visited.add(currentName);
		NodeTypeDefinition nt = map.get(currentName);
		if (nt == null) return;
		if (nt.getProperties() != null && nt.getProperties().getProperties() != null) {
			for (TypeProperty prop : nt.getProperties().getProperties()) {
				results.add(prop.getName());
			}
		}
		if (nt.getSuperTypes() != null) {
			for (String parentName : nt.getSuperTypes()) {
				collectInheritedPropertyNames(parentName, map, results, visited);
			}
		}
	}
}
