/*
 * openCypher Xtext - Slizaa Static Software Analysis Tools
 * Copyright © ${year} Code-Kontor GmbH and others (slizaa@codekontor.io)
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Code-Kontor GmbH - initial API and implementation
 */
/*
 * generated by Xtext 2.10.0
 */
package io.codekontor.opencypher.xtext.validation;

import java.util.regex.Pattern;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.validation.Check;
import io.codekontor.opencypher.xtext.openCypher.DecimalInteger;
import io.codekontor.opencypher.xtext.openCypher.LegacyParameter;
import io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage;
import io.codekontor.opencypher.xtext.openCypher.Parameter;
import io.codekontor.opencypher.xtext.openCypher.RangeLiteral;
import io.codekontor.opencypher.xtext.openCypher.Return;
import io.codekontor.opencypher.xtext.openCypher.VersionNumber;
import io.codekontor.opencypher.xtext.openCypher.Cypher;
import com.google.inject.name.Named;
import com.google.inject.Inject;

/**
 * This class implements custom validation rules for the openCypher language.
 *
 * Semantic rules defined here go beyond the capabilities of a context-free grammar,
 * allowing the editor to flag logical errors such as misplaced clauses or
 * incorrectly formatted literals.
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class OpenCypherValidator extends AbstractOpenCypherValidator {

	/** Regular expression to validate version numbers. */
	private static final Pattern VERSION_NUMBER_FORMAT = Pattern.compile("\\d*\\.\\d*");

	/** Regular expression to validate that decimal integers do not start with a leading zero. */
	private static final Pattern DECIMAL_INTEGER_FORMAT = Pattern.compile("[1..9]*\\d*");

	/** Unique error keys used to identify specific validation failures in the UI. */
	public static final String INVALID_VERSION_NUMBER_FORMAT = "invalidVersionNumber";
	public static final String INVALID_DECIMAL_INTEGER_FORMAT = "invalidDecimalInteger";
	public static final String INVALID_STATEMENT_COUNT = "invalidStatementCount";
	public static final String RETURN_NOT_AT_THE_END = "returnNotAtTheEnd";

	/**
	 * Configuration setting to determine if a single file can contain multiple
	 * Cypher statements separated by semicolons.
	 */
	@Inject(optional=true)
	@Named("opencypher.allowMultipleStatements")
	private boolean allowMultipleStatements = false;

	/**
	 * Validates that the input contains the correct number of statements.
	 *
	 * If multiple statements are provided but the configuration disallows it,
	 * an error is attached to the statement list feature.
	 */
	@Check
	public void checkCypherFormat(Cypher cypher) {

		if (allowMultipleStatements) {
			return;
		}

		// Ensure that exactly one statement is present if multiple statements are restricted.
		if (cypher.getStatements().size() != 1) {
			error("There must be exactly one statement.",
					OpenCypherPackage.eINSTANCE.getCypher_Statements(), INVALID_STATEMENT_COUNT);
		}
	}

	/**
	 * Placeholder for legacy parameter validation.
	 */
	@Check
	public void checkLegacyParameterFormat(LegacyParameter legacyParameter) {
		// TODO check!
		// legacyParameter : '{' ws ( symbolicName | DecimalInteger ) ws '}' ;
	}

	/**
	 * Placeholder for standard parameter validation.
	 */
	@Check
	public void checkParameterFormat(Parameter parameter) {
		// TODO check!
		// parameter : '$' ( symbolicName | DecimalInteger ) ;
	}

	/**
	 * Placeholder for range literal validation.
	 */
	@Check
	public void checkRangeLiteralFormat(RangeLiteral rangeLiteral) {
		// TODO check!
		rangeLiteral.getLower();
		// TODO check!
		rangeLiteral.getUpper();
	}

	/**
	 * Verifies that decimal integer literals follow the required numeric format.
	 *
	 * Even though the lexer identifies these as numbers, this method ensures
	 * they meet domain-specific formatting rules.
	 */
	@Check
	public void checkDecimalIntegerFormat(DecimalInteger decimalInteger) {
		if (!DECIMAL_INTEGER_FORMAT.matcher(decimalInteger.getValue()).matches()) {
			error("Version number must have the following format: (digit)+'.'(digit)+",
					OpenCypherPackage.eINSTANCE.getDecimalInteger_Value(), INVALID_DECIMAL_INTEGER_FORMAT);
		}
	}

	/**
	 * Ensures that the Cypher version number is correctly formatted.
	 */
	@Check
	public void checkVersionNumberFormat(VersionNumber versionNumber) {
		if (versionNumber.getVersionNumber() != null) {
			if (!VERSION_NUMBER_FORMAT.matcher(versionNumber.getVersionNumber()).matches()) {
				error("Version number must have the following format: (digit)+'.'(digit)+",
						OpenCypherPackage.eINSTANCE.getVersionNumber_VersionNumber(), INVALID_VERSION_NUMBER_FORMAT);
			}
		}
	}

	/**
	 * Validates the placement of the RETURN clause within a query.
	 */
	@Check
	public void checkReturn(Return ret) {
		if (EcoreUtil2.getNextSibling(ret) != null) {
			error("RETURN can only be used once at the end of the query", ret,
					OpenCypherPackage.eINSTANCE.getReturn_Return(), RETURN_NOT_AT_THE_END);
		}
	}
}
