/*
 * openCypher Xtext - Slizaa Static Software Analysis Tools
 * Copyright © ${year} Code-Kontor GmbH and others (slizaa@codekontor.io)
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Code-Kontor GmbH - initial API and implementation
 */
/*
 * generated by Xtext 2.10.0
 */
package io.codekontor.opencypher.xtext.scoping;

import io.codekontor.opencypher.xtext.openCypher.*;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;

/**
 * Main Scope provider for the openCypher grammar.
 * It manages how variables are discovered and linked throughout a Cypher query.
 */
public class OpenCypherScopeProvider extends AbstractOpenCypherScopeProvider {

	/**
	 * Entry point for scope resolution.
	 */
	@Override
	public IScope getScope(EObject context, EReference reference) {
		// Check if we are currently looking for the definition of a variable reference
		if (context instanceof VariableRef && reference == OpenCypherPackage.Literals.VARIABLE_REF__VARIABLE_REF) {

			// Collect declarations from three possible sources of variables in Cypher
			Iterable<VariableDeclaration> elementsFromStatement = extractDeclarationsFromClauses(context);
			Iterable<VariableDeclaration> elementsFromExpression = extractDeclarationsFromExpression(context);
			Iterable<VariableDeclaration> elementsFromForeach = extractDeclarationsFromForeach(context);

			// Merge all found declarations into a single list
			List<VariableDeclaration> allElements = new ArrayList<>();
			elementsFromExpression.forEach(allElements::add);
			elementsFromForeach.forEach(allElements::add);
			elementsFromStatement.forEach(allElements::add);

			// Return a scope containing all valid variable definitions found
			return Scopes.scopeFor(allElements);
		}

		// Handle references where the target type is a NodeTypeDefinition
		if (reference.getEReferenceType().getInstanceClass() == NodeTypeDefinition.class) {
			// Collect all NodeTypeDefinitions from the entire resource
			List<NodeTypeDefinition> allTypes = EcoreUtil2.getAllContentsOfType(context.eResource().getContents().get(0), NodeTypeDefinition.class);
			// Prevent self-inheritance
			if (context instanceof NodeTypeDefinition) allTypes.remove(context);
			// Create the scope using a custom name provider lambda.
			// Since NodeTypeDefinition doesn't have a 'name' attribute, we explicitly map to the 'labelName' property within its 'label' object for linking.
			return Scopes.scopeFor(allTypes, obj -> ((NodeTypeDefinition)obj).getLabel().getLabelName(), null);
		}

		// Fallback to default Xtext behavior for other types of references
		return super.getScope(context, reference);
	}

	/**
	 * Finds the top-level Statement and starts extracting variables defined in its various clauses.
	 */
	protected Iterable<VariableDeclaration> extractDeclarationsFromClauses(EObject context) {
		// Traverse up the tree to find the root Statement object
		Statement statement = EcoreUtil2.getAllContainers(context).stream()
				.filter(Statement.class::isInstance)
				.map(Statement.class::cast)
				.reduce((first, second) -> second)
				.orElse(null);

		if (statement == null) return Collections.emptyList();
		return extractDeclarationsFromStatement(statement, context);
	}

	/**
	 * Differentiates between query types.
	 */
	protected Iterable<VariableDeclaration> extractDeclarationsFromStatement(EObject statement, EObject context) {
		if (statement instanceof RegularQuery) {
			// In a regular query, we find the clauses and filter based on where we are
			RegularQuery regularQuery = (RegularQuery) statement;
			Clause contextClause = EcoreUtil2.getContainerOfType(context, Clause.class);
			SinglePartQuery spq = EcoreUtil2.getContainerOfType(context, SinglePartQuery.class);
			MultiPartQuery mpq = EcoreUtil2.getContainerOfType(context, MultiPartQuery.class);

			List<? extends Clause> clauses = (mpq == null) ? extractClauses(spq) : extractClauses(mpq);
			return extractDeclarationsFromClauseList(clauses, contextClause, context);

		} else if (statement instanceof BulkImportQuery) {
			BulkImportQuery bulkImportQuery = (BulkImportQuery) statement;
			Clause contextClause = EcoreUtil2.getContainerOfType(context, Clause.class);
			List<? extends Clause> clauses = extractClauses(bulkImportQuery.getLoadCSVQuery().getSingleQuery());
			return extractDeclarationsFromClauseList(clauses, contextClause, context);

		} else if (statement instanceof Command) {
			return EcoreUtil2.getAllContentsOfType(statement, VariableDeclaration.class);
		}
		return Collections.emptyList();
	}

	/**
	 * Flattens a Query structure into a linear list of Clauses.
	 */
	protected List<? extends Clause> extractClauses(SingleQuery sq) {
		if (sq instanceof SinglePartQuery) {
			SinglePartQuery spq = (SinglePartQuery) sq;
			List<Clause> clauses = new ArrayList<>();
			clauses.addAll(spq.getReadingClauses());
			clauses.addAll(spq.getUpdatingClauses());
			if (spq.getReturn() != null) clauses.add(spq.getReturn());
			return clauses;
		} else if (sq instanceof MultiPartQuery) {
			MultiPartQuery mpq = (MultiPartQuery) sq;
			List<Clause> clauses = mpq.getSubQueries().stream()
					.flatMap(sub -> extractClausesFromMultiPartSubQuery(sub).stream())
					.collect(Collectors.toList());
			clauses.addAll(extractClauses(mpq.getSinglePartQuery()));
			return clauses;
		}
		return Collections.emptyList();
	}

	/**
	 * Extracts clauses from a part of a multi-part query.
	 */
	protected List<? extends Clause> extractClausesFromMultiPartSubQuery(MultiPartSubQuery mpsq) {
		List<Clause> clauses = new ArrayList<>();
		clauses.addAll(mpsq.getReadingClauses());
		clauses.addAll(mpsq.getUpdatingClauses());
		if (mpsq.getWithPart() != null) clauses.add(mpsq.getWithPart());
		return clauses;
	}

	/**
	 * Determines which previous clauses are visible to the current position.
	 */
	protected Iterable<VariableDeclaration> extractDeclarationsFromClauseList(List<? extends Clause> clauses, Clause contextClause, EObject context) {
		List<VariableDeclaration> elements = new ArrayList<>();
		MergeAction mergeAction = EcoreUtil2.getContainerOfType(context, MergeAction.class);
		Clause currentClause = (mergeAction != null) ? EcoreUtil2.getContainerOfType(mergeAction, Clause.class) : contextClause;

		int offset = 0;
		if (contextClause instanceof Unwind) {
			offset = -1;
		} else if (currentClause instanceof With || currentClause instanceof Return) {
			if (EcoreUtil2.getContainerOfType(context, Order.class) != null || EcoreUtil2.getContainerOfType(context, Where.class) != null) {
				offset = 0;
			} else {
				offset = -1;
			}
		}

		int startClauseIndex = clauses.indexOf(currentClause) + offset;
		for (int i = startClauseIndex; i >= 0; i--) {
			Clause clause = clauses.get(i);
			List<VariableDeclaration> declarations = EcoreUtil2.getAllContentsOfType(clause, VariableDeclaration.class);
			for (VariableDeclaration dec : declarations) {
				if (elements.stream().noneMatch(e -> e.getName().equals(dec.getName()))) {
					elements.add(dec);
				}
			}
		}
		return elements;
	}

	/**
	 * Handles scoping for variables defined inside expressions.
	 */
	protected Iterable<VariableDeclaration> extractDeclarationsFromExpression(EObject context) {
		Expression expression = EcoreUtil2.getContainerOfType(context.eContainer(), Expression.class);
		if (expression == null) return Collections.emptyList();

		List<VariableDeclaration> declarations = new ArrayList<>();
		extractDeclarationsFromSingleExpression(expression).forEach(declarations::add);

		List<Expression> outerExpressions = EcoreUtil2.getAllContainers(expression).stream()
				.filter(Expression.class::isInstance)
				.map(Expression.class::cast)
				.collect(Collectors.toList());

		outerExpressions.forEach(oe -> extractDeclarationsFromSingleExpression(oe).forEach(declarations::add));
		return declarations;
	}

	/**
	 * Extracts variables from specific Cypher expression.
	 */
	protected Iterable<VariableDeclaration> extractDeclarationsFromSingleExpression(Expression expression) {
		FilterExpression filterExpression = extractFilterExpression(expression);

		if (filterExpression != null) {
			return Collections.singletonList(filterExpression.getIdInColl().getVariable());
		} else if (expression instanceof Reduce) {
			Reduce reduce = (Reduce) expression;
			return Stream.of(reduce.getAccumulator(), reduce.getIdInColl().getVariable()).collect(Collectors.toList());
		} else if (expression instanceof PatternComprehension) {
			PatternComprehension pc = (PatternComprehension) expression;
			List<VariableDeclaration> vars = new ArrayList<>();
			if (pc.getPathVariable() != null) vars.add(pc.getPathVariable());
			vars.addAll(EcoreUtil2.getAllContentsOfType(pc.getPattern(), VariableDeclaration.class));
			return vars;
		}
		return Collections.emptyList();
	}

	/**
	 * Helper to find filter expressions in various collection-based Cypher functions.
	 */
	protected FilterExpression extractFilterExpression(Expression e) {
		if (e instanceof ListComprehension) return ((ListComprehension) e).getFilterExpression();
		if (e instanceof Extract) return ((Extract) e).getFilterExpression();
		if (e instanceof Filter) return ((Filter) e).getFilterExpression();
		if (e instanceof All) return ((All) e).getFilterExpression();
		if (e instanceof Any) return ((Any) e).getFilterExpression();
		if (e instanceof None) return ((None) e).getFilterExpression();
		if (e instanceof Single) return ((Single) e).getFilterExpression();
		return null;
	}

	/**
	 * Handles variables defined within a FOREACH loop.
	 */
	protected Iterable<VariableDeclaration> extractDeclarationsFromForeach(EObject context) {
		Foreach foreach = EcoreUtil2.getContainerOfType(context, Foreach.class);
		if (foreach == null) return Collections.emptyList();

		SingleQuery sq = EcoreUtil2.getContainerOfType(context, SingleQuery.class);
		List<? extends Clause> clauses = extractClauses(sq);
		Iterable<VariableDeclaration> declarationsFromClauses = extractDeclarationsFromClauseList(clauses, foreach, context);

		List<VariableDeclaration> results = new ArrayList<>();
		results.add(foreach.getVariable());
		extractDeclarationsFromForeach(context.eContainer()).forEach(results::add);
		declarationsFromClauses.forEach(results::add);
		return results;
	}
}
