/*
 * openCypher Xtext - Slizaa Static Software Analysis Tools
 * Copyright © ${year} Code-Kontor GmbH and others (slizaa@codekontor.io)
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Code-Kontor GmbH - initial API and implementation
 */
/*
 * generated by Xtext 2.21.0
 */
package io.codekontor.opencypher.xtext;


/**
 * The OpenCypherRuntimeModule class is a central configuration point used to register
 * and wire language components at runtime.
 *
 * This class extends AbstractOpenCypherRuntimeModule, which contains the default
 * service bindings generated by Xtext. Developers can override or add
 * new methods here to provide custom implementations for various language services.
 */
public class OpenCypherRuntimeModule extends AbstractOpenCypherRuntimeModule {
	// This class currently uses the default service bindings provided by the base class.
}
